StoreFront.UI.MVC/Controllers/EquipmentsController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StoreFront.DATA.EF.Models;
using StoreFront.UI.MVC.Utilities;
using X.PagedList; //Paged List - Step 2

namespace StoreFront.UI.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class EquipmentsController : Controller
    {
        private readonly StoreFrontContext _context;

        private readonly IWebHostEnvironment _webHostEnvironment;

        //    public EquipmentsController(StoreFrontContext context, IWebHostEnvironment webHostEnvironment)
        //    {
        //        _context = context;
        //        _webHostEnvironment = webHostEnvironment;
        //    }
        public EquipmentsController(StoreFrontContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Equipments
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var storeFrontContext = _context.Equipment.Include(e => e.EquipmentType).Include(e => e.Status).Include(e => e.Store);
            return View(await storeFrontContext.ToListAsync());
        }

        #region Filter/Paging Steps
        //---- SEARCH ----//
        //1) Create form in the view (for the SEARCH portion, only need 1 textbox and a submit button - <select> will be added later)
        //2) Update controller Action ([A] add param, [B]add search filter logic)

        //---- DDL ----//
        //1) Create ViewData[] object in Controller action (this sends DDL list to the View)
        //2) Add <select> inside of <form>
        //3) Update Controller Action ([A] add param, [B] add category filter logic)

        //---- PAGED LIST ----//
        //1) Install package for X.PagedList.Mvc.Core
        //      - Open Package Manger Console -> select the UI project -> install-package x.pagedlist.mvc.core
        //2) Add using statements and update model declaration in the View
        //3) Add param to Controller Action
        //4) Add page size variable in Action
        //5) Update return statement in Controller Action
        //6) Add Counter in View

        // 7) Create a new CSS file in wwwroot/css named 'PagedList.css'
        //      - NOTE: may need to go to the package's NuGet page and copy the CSS directly OR copy from an existing project :)
        //      - X.PagedList CSS file link (go here to copy the code): https://github.com/dncuug/X.PagedList/blob/master/examples/X.PagedList.Mvc.Example.Core/wwwroot/css/PagedList.css
        // 0) Add a <link> to the _Layout referencing 'PagedList.css'
        #endregion


        [AllowAnonymous]
        //public async Task<IActionResult> TiledView()
        //{
        //    var storeFrontContext = _context.Equipment.Include(e => e.EquipmentType).Include(e => e.Status).Include(e => e.Store);
        //    return View(await storeFrontContext.ToListAsync());
        //}

        public async Task<IActionResult> TiledView(string searchTerm, int categoryId = 0 , int page = 1)
        {
            int pageSize = 6;

            var equipment = _context.Equipment.Where(e => e.StatusId != 4)
                .Include(e => e.EquipmentType).Include(e => e.Store).Include(e => e.OrderEquipments).ToList();

            ViewData["EquipmentTypeId"] = new SelectList(_context.EquipmentTypes, "EquipmentTypeId", "TypeName");

            if (categoryId != 0)
            {
                equipment = equipment.Where(e => e.EquipmentTypeId == categoryId).ToList();

                ViewData["EquipmentTypeId"] = new SelectList(_context.EquipmentTypes, "EquipmentTypeId", "TypeName");
            }

            if (!String.IsNullOrEmpty(searchTerm))
            {
                equipment = equipment.Where(e =>
                                                e.EquipmentName.ToLower().Contains(searchTerm.ToLower())
                                                || e.Store.StoreName.ToLower().Contains(searchTerm.ToLower())
                                                || (e.EquipmentDescription != null && e.EquipmentDescription.ToLower().Contains(searchTerm.ToLower()))
                                                || e.EquipmentType.TypeName.ToLower().Contains(searchTerm.ToLower())).ToList();

                ViewBag.SearchTerm = searchTerm;
                ViewBag.NbrResults = equipment.Count;
            }
            else
            {
                ViewBag.SearchTerm = null;
                ViewBag.NbrResults = null;
            }

            return View(equipment.ToPagedList(page, pageSize));
        }


        // GET: Equipments/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Equipment == null)
            {
                return NotFound();
            }

            var equipment = await _context.Equipment
                .Include(e => e.EquipmentType)
                .Include(e => e.Status)
                .Include(e => e.Store)
                .FirstOrDefaultAsync(m => m.EquipmentId == id);
            if (equipment == null)
            {
                return NotFound();
            }

            return View(equipment);
        }

        // GET: Equipments/Create

        public IActionResult Create()
        {
            ViewData["EquipmentTypeId"] = new SelectList(_context.EquipmentTypes, "EquipmentTypeId", "TypeName");
            ViewData["StatusId"] = new SelectList(_context.EquipmentStatuses, "StatusId", "StatusName");
            ViewData["StoreId"] = new SelectList(_context.GolfStores, "StoreId", "StoreName");
            return View();
        }

        // POST: Equipments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Create([Bind("EquipmentId,EquipmentName,EquipmentPrice,EquipmentDescription,StoreId,EquipmentTypeId,StatusId,ProductImage, UnitsInStock")] Equipment equipment)
        {
            if (ModelState.IsValid)
            {
                if (equipment.Image != null)
                {
                    string ext = Path.GetExtension(equipment.Image.FileName);

                    string[] validExts = { ".jpeg", ".jpg", ".gif", ".png" };

                    if (validExts.Contains(ext.ToLower()) && equipment.Image.Length < 4_194_303)
                    {
                        equipment.ProductImage = Guid.NewGuid() + ext;

                        string iAmRoot = _webHostEnvironment.WebRootPath;

                        string fullImage = iAmRoot + "/images";

                        using (var memoryStream = new MemoryStream())
                        {
                            await equipment.Image.CopyToAsync(memoryStream);

                            using (var img = Image.FromStream(memoryStream))
                            {
                                int maxImageSize = 500; //size in pixels
                                int maxThumbSize = 100; //size in pixels

                                ImageUtility.ResizeImage(iAmRoot, equipment.ProductImage, img, maxImageSize, maxThumbSize);

                                //myFile.Save("path/to/folder", "filename") > How to save something 
                                //that is NOT an image.

                            }
                        }
                    }
                }

                else
                {
                    equipment.ProductImage = "noimage.png";
                }


                _context.Add(equipment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EquipmentTypeId"] = new SelectList(_context.EquipmentTypes, "EquipmentTypeId", "TypeName", equipment.EquipmentTypeId);
            ViewData["StatusId"] = new SelectList(_context.EquipmentStatuses, "StatusId", "StatusName", equipment.StatusId);
            ViewData["StoreId"] = new SelectList(_context.GolfStores, "StoreId", "StoreName", equipment.StoreId);
            return View(equipment);
        }

        // GET: Equipments/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Equipment == null)
            {
                return NotFound();
            }

            var equipment = await _context.Equipment.FindAsync(id);
            if (equipment == null)
            {
                return NotFound();
            }
            ViewData["EquipmentTypeId"] = new SelectList(_context.EquipmentTypes, "EquipmentTypeId", "TypeName", equipment.EquipmentTypeId);
            ViewData["StatusId"] = new SelectList(_context.EquipmentStatuses, "StatusId", "StatusName", equipment.StatusId);
            ViewData["StoreId"] = new SelectList(_context.GolfStores, "StoreId", "StoreName", equipment.StoreId);
            return View(equipment);
        }

        // POST: Equipments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("EquipmentId,EquipmentName,EquipmentPrice,EquipmentDescription,StoreId,EquipmentTypeId,StatusId,ProductImage, UnitsInStock")] Equipment equipment)
        {
            if (id != equipment.EquipmentId)
            {
                return NotFound();
            }

StoreFront.UI.MVC/Controllers/GolfStoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StoreFront.DATA.EF.Models;

namespace StoreFront.UI.MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class GolfStoresController : Controller
    {
        private readonly StoreFrontContext _context;

        public GolfStoresController(StoreFrontContext context)
        {
            _context = context;
        }

        // GET: GolfStores
        public async Task<IActionResult> Index()
        {
              return View(await _context.GolfStores.ToListAsync());
        }

        // GET: GolfStores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.GolfStores == null)
            {
                return NotFound();
            }

            var golfStore = await _context.GolfStores
                .FirstOrDefaultAsync(m => m.StoreId == id);
            if (golfStore == null)
            {
                return NotFound();
            }

            return View(golfStore);
        }

        // GET: GolfStores/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: GolfStores/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StoreId,StoreName,PhoneNumber,Region,Country,ZipCode,State,Address")] GolfStore golfStore)
        {
            if (ModelState.IsValid)
            {
                _context.Add(golfStore);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(golfStore);
        }

        // GET: GolfStores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.GolfStores == null)
            {
                return NotFound();
            }

            var golfStore = await _context.GolfStores.FindAsync(id);
            if (golfStore == null)
            {
                return NotFound();
            }
            return View(golfStore);
        }

        // POST: GolfStores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StoreId,StoreName,PhoneNumber,Region,Country,ZipCode,State,Address")] GolfStore golfStore)
        {
            if (id != golfStore.StoreId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(golfStore);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GolfStoreExists(golfStore.StoreId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(golfStore);
        }

        // GET: GolfStores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.GolfStores == null)
            {
                return NotFound();
            }

            var golfStore = await _context.GolfStores
                .FirstOrDefaultAsync(m => m.StoreId == id);
            if (golfStore == null)
            {
                return NotFound();
            }

            return View(golfStore);
        }

        // POST: GolfStores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.GolfStores == null)
            {
                return Problem("Entity set 'StoreFrontContext.GolfStores'  is null.");
            }
            var golfStore = await _context.GolfStores.FindAsync(id);
            if (golfStore != null)
            {
                _context.GolfStores.Remove(golfStore);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GolfStoreExists(int id)
        {
          return _context.GolfStores.Any(e => e.StoreId == id);
        }
    }
}

StoreFront.UI.MVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> signInManager


<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    @*<link rel="shortcut icon" href="~/img/fav.png">*@
    <link rel="shortcut icon" href="~/img/storefrontphotos/logo/1.png">
    <!-- Author Meta -->
    <meta name="author" content="CodePixar">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>@ViewData["Title"] | Store Front</title>
    <!--
        CSS
        ============================================= -->
    <link rel="stylesheet" href="~/css/linearicons.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/themify-icons.css">
    <link rel="stylesheet" href="~/css/bootstrap.css">
    <link rel="stylesheet" href="~/css/owl.carousel.css">
    <link rel="stylesheet" href="~/css/nice-select.css">
    <link rel="stylesheet" href="~/css/nouislider.min.css">
    <link rel="stylesheet" href="~/css/ion.rangeSlider.css" />
    <link rel="stylesheet" href="~/css/ion.rangeSlider.skinFlat.css" />
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/main.css">

    <!--Paged List Styles-->
    <link rel="stylesheet" href="~/css/PagedList.css" />
</head>

<body>


    <!-- Start Header Area -->
    <header class="header_area sticky-header">
        <div class="main_menu">
            <nav class="navbar navbar-expand-lg navbar-light main_box">
                <div class="container">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <a class="navbar navbar-brand" href="~/"><img src="~/img/storefrontphotos/logo/capture.JPG" alt="#"></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                        <ul class="nav navbar-nav menu_nav ml-auto">
                            <li class="nav-item active"><a class="nav-link" href="~/">Home</a></li>      
                            <li class="nav-item"><a asp-action="Index" asp-controller="Equipments" class="nav-link">Shop</a></li>                            
                            

                                    @*<ul class="dropdown-menu">
                                        <li><a asp-action="Index" asp-controller="EquipmentTypes">Shop Equipment</a></li>
                                        <li><a asp-action="Index" asp-controller="Equipments">Product Details</a></li>
                                        <li><a asp-action="Checkout" asp-controller="Shop">Checkout</a></li>
                                        <li><a asp-action="ShoppingCart" asp-controller="Shop">Shopping Cart</a></li>
                                    <li><a asp-action="Confirmation" asp-controller="Shop">Confirmation</a></li>
                                    </ul>*@                                

                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item submenu dropdown">
                                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                                   aria-expanded="false">Admin</a>
                                    <ul class="dropdown-menu">
                                        <li><a asp-action="ListUsers" asp-controller="Administration">Users</a></li>
                                        <li><a asp-action="ListRoles" asp-controller="Administration">Roles</a></li>
                                        <li><a asp-action="Index" asp-controller="GolfStores">Suppliers</a></li>
                                        <li><a asp-action="Index" asp-controller="EquipmentTypes">Categories</a></li>
                                    </ul>
                                </li>

                            }
                            
                            @if (signInManager.IsSignedIn(User))
                            {
                                <li class="nav-item"><a asp-action="Index" asp-controller="EquipmentTypes" class="nav-link">Categories</a></li>

                            }

                            <li class="nav-item"><a asp-action="Contact" asp-controller="Home" class="nav-link">Contact</a></li>

                            <li class="nav-item submenu dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                                   aria-expanded="false">Login</a>
                                <ul class="dropdown-menu">
                                    <partial name="_LoginPartial" />
                                </ul>
                            </li>

                        </ul>


                        <ul class="nav navbar-nav navbar-right">
                            <li class="nav-item"><a class="nav-link" asp-action="Index" asp-controller="ShoppingCart"><span class="ti-bag"></span></a></li>
                            <li class="nav-item">
                                <button class="search"><span class="lnr lnr-magnifier" id="search"></span></button>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <div class="search_input" id="search_input_box">
            <div class="container">
                <form class="d-flex justify-content-between">
                    <input type="text" class="form-control" id="search_input" placeholder="Search Here">
                    <button type="submit" class="btn"></button>
                    <span class="lnr lnr-close" id="close_search" title="Close Search"></span>
                </form>
            </div>
        </div>
    </header>
    <!-- End Header Area -->
    @RenderSection("Banner", required: false)


    @RenderBody()

    <!-- start footer Area -->
    <footer class="footer-area section_gap">
        <div class="container">
            <div class="row">
                <div class="col-lg-4  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>About Us</h6>
                        <p>
                            Here at GolfLinqs, we pride ourself on our One on One customer service and staff expertise.
                        </p>
                    </div>
                </div>
                <div class="col-lg-4  col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h6>Newsletter</h6>
                        <p>Stay update with our latest</p>
                        <div class="" id="mc_embed_signup">

                            <form target="_blank" novalidate="true" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                                  method="get" class="form-inline">

                                <div class="d-flex flex-row">

                                    <input class="form-control" name="EMAIL" placeholder="Enter Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Email '"
                                           required="" type="email">


                                    <button class="click-btn btn btn-default"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></button>
                                    <div style="position: absolute; left: -5000px;">
                                        <input name="b_36c4fd991d266f23781ded980_aefe40901a" tabindex="-1" value="" type="text">
                                    </div>

                                    <div class="col-lg-4 col-md-4">
                                        <button class="bb-btn btn"><span class="lnr lnr-arrow-right"></span></button>
                                    </div>
                                </div>
                                <div class="info"></div>
                            </form>
                        </div>
                    </div>
                </div>
                
            </div>
            <div class="footer-bottom d-flex justify-content-center align-items-center flex-wrap">
                <p class="footer-text m-0">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    &copy;<script>document.write(new Date().getFullYear());</script> <strong>Golf Linq | John Walls</strong>. All rights reserved.
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </footer>
    <!-- End footer Area -->

    <script src="js/vendor/jquery-2.2.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
            crossorigin="anonymous"></script>
    <script src="~/js/vendor/bootstrap.min.js"></script>
    <script src="~/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <script src="~/js/jquery.sticky.js"></script>
    <script src="~/js/nouislider.min.js"></script>
    <script src="~/js/countdown.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <!--gmaps Js-->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
    <script src="~/js/gmaps.min.js"></script>
    <script src="~/js/main.js"></script>

    @RenderSection("Scripts", required: false)

</body>

</html>

StoreFront.UI.MVC/Views/Shared/_OriginalLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StoreFront.UI.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StoreFront.UI.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StoreFront.UI.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - StoreFront.UI.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>